apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
- target:
    group: ""
    kind: ConfigMap
  patch: |-
    - op: replace
      path: /data
      value:
        cluster: cluster-c
